backend:
  name: github
  repo: mathieu-kosmio/DataWood-Consortium
  branch: main
  site_url: http://localhost:3000

local_backend: true

title: "DataWood CMS"
media_folder: "public/img"
public_folder: "/img"

collections:
  # Collection for the Blog
  - name: "blog"
    label: "Articles de Blog"
    folder: "src/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date de publication", name: "date", widget: "datetime" }
      - { label: "Auteur", name: "author", widget: "string", default: "DataWood Team" }
      - { label: "Image de couverture", name: "image", widget: "image", required: false }
      - { label: "Résumé", name: "description", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list", default: ["News"] }
      - { label: "Contenu", name: "body", widget: "markdown" }
