
backend:
  name: github
  repo: mathieu-kosmio/DataWood-Consortium
  branch: main
  site_url: https://qwc48o4sow8ck80c4cws0okk.51.91.166.222.sslip.io

title: "Kosmio Technology"

media_folder: public/img
public_folder: /img

collections:
  - name: pages
    label: Pages Principales
    files:
      - name: home
        label: Accueil
        file: public/docs/home.md
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: text }
          - { label: Body, name: body, widget: markdown }
      - name: manifesto
        label: Manifeste
        file: public/docs/manifesto.md
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: text }
          - { label: Body, name: body, widget: markdown }

  - name: governance
    label: Gouvernance
    folder: public/docs/governance
    create: true
    extension: "md"
    slug: "{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: text }
      - { label: Status, name: status, widget: select, options: ["draft", "stable", "deprecated"], default: "draft" }
      - { label: Body, name: body, widget: markdown }

  - name: architecture
    label: Architecture
    folder: public/docs/architecture
    create: true
    extension: "md"
    slug: "{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: text }
      - { label: Status, name: status, widget: select, options: ["draft", "stable", "deprecated"], default: "draft" }
      - { label: Body, name: body, widget: markdown }
